### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by andreis** [lavab/oss#1]
`DEV`

**Comment by 3nsoft** [comment]
README would be lovely.
I guess, the best way would be to run this inside a virtual machine?

**Comment by andreis** [comment]
This repo is WIP. I'm planning to support Docker, Vagrant, Sandstorm, Ubuntu/Fedora, OS X, Windows, but at first, yes, it will most likely be targeted at some Ubuntu running in a VM.

**Comment by flixi** [comment]
Solved, for Running in docker, others to follow.
